package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"

	"github.com/konradreiche/re/internal/commandtest/fakegithub/graph/model"
)

// Repository is the resolver for the repository field.
func (r *queryResolver) Repository(ctx context.Context, followRenames *bool, name string, owner string) (*model.Repository, error) {
	return r.Resolver.Repository, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, after *string, before *string, first *int32, last *int32, query string, typeArg model.SearchType) (*model.SearchResultItemConnection, error) {
	return &model.SearchResultItemConnection{}, nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.User, error) {
	return r.Resolver.Viewer, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
